package bob;

import java.io.IOException;
import java.time.LocalDate;

import bob.exception.BobException;
import bob.parser.Parser;
import bob.storage.Storage;
import bob.task.Task;
import bob.task.TaskList;
import bob.ui.Ui;

/**
 * Starts the Bob chatbot application.
 */
public class Bob {
    private final Storage storage;
    private final TaskList tasks;
    private final Ui ui;
    private final String loadingError;
    private boolean isExit;

    /**
     * Creates Bob and loads tasks from the given storage file.
     *
     * @param filePath path of the file used to store tasks
     */
    public Bob(String filePath) {
        assert filePath != null && !filePath.isBlank() : "Storage path must not be null or blank";
        ui = new Ui();
        storage = new Storage(filePath);

        TaskList loadedTasks;
        String loadError = null;
        try {
            loadedTasks = new TaskList(storage.loadTasks());
        } catch (IOException | BobException e) {
            loadError = e.getMessage();
            loadedTasks = new TaskList();
        }
        tasks = loadedTasks;
        loadingError = loadError;
    }

    /**
     * Runs Bob's command loop until the user enters {@code bye}.
     */
    public void run() {
        ui.showWelcome();
        if (loadingError != null) {
            ui.showMessage(ui.getLoadingErrorMessage(loadingError));
        }

        while (ui.hasNextCommand()) {
            String command = ui.readCommand();
            ui.showLine();
            ui.showMessage(getResponse(command));
            ui.showLine();
            if (isExit) {
                break;
            }
        }
    }

    /**
     * Executes one command and returns the response for either a console or graphical UI.
     *
     * @param command command entered by the user
     * @return response to display
     */
    public String getResponse(String command) {
        assert command != null : "Command from the UI must not be null";
        try {
            return executeCommand(command.trim());
        } catch (BobException e) {
            return e.getMessage();
        } catch (IOException e) {
            return ui.getSavingErrorMessage();
        }
    }

    /**
     * Dispatches a validated command to the corresponding task operation.
     *
     * @param input trimmed command entered by the user
     * @return response generated by the command
     * @throws BobException if the command or its arguments are invalid
     * @throws IOException if a task change cannot be saved
     */
    private String executeCommand(String input) throws BobException, IOException {
        if (input.equals("bye")) {
            isExit = true;
            return ui.getGoodbyeMessage();
        }
        if (input.equals("list")) {
            return ui.getTaskListMessage(tasks.getTasks());
        }
        if (Parser.isCommand(input, "find")) {
            String keyword = Parser.parseFindKeyword(input);
            return ui.getMatchingTasksMessage(tasks.find(keyword));
        }
        if (Parser.isCommand(input, "schedule")) {
            LocalDate date = Parser.parseScheduleDate(input);
            return ui.getScheduleMessage(date, tasks.getSchedule(date));
        }
        if (Parser.isCommand(input, "mark")) {
            return markTask(input);
        }
        if (Parser.isCommand(input, "unmark")) {
            return unmarkTask(input);
        }
        if (Parser.isCommand(input, "delete")) {
            return deleteTask(input);
        }
        if (Parser.isCommand(input, "todo")) {
            return addTask(Parser.parseTodo(input));
        }
        if (Parser.isCommand(input, "deadline")) {
            return addTask(Parser.parseDeadline(input));
        }
        if (Parser.isCommand(input, "event")) {
            return addTask(Parser.parseEvent(input));
        }
        throw new BobException("I couldn't match that to a command. "
                + "Try todo, deadline, event, list, find, schedule, mark, unmark, delete, or bye.");
    }

    /**
     * Marks a task and saves its updated status.
     *
     * @param input full mark command
     * @return task-marked response
     * @throws BobException if the task number is invalid
     * @throws IOException if the task list cannot be saved
     */
    private String markTask(String input) throws BobException, IOException {
        int taskNumber = Parser.parseTaskNumber(input, "mark", tasks.size());
        String markedTask = tasks.mark(taskNumber);
        storage.saveTasks(tasks.getTasks());
        return ui.getTaskMarkedMessage(markedTask);
    }

    /**
     * Unmarks a task and saves its updated status.
     *
     * @param input full unmark command
     * @return task-unmarked response
     * @throws BobException if the task number is invalid
     * @throws IOException if the task list cannot be saved
     */
    private String unmarkTask(String input) throws BobException, IOException {
        int taskNumber = Parser.parseTaskNumber(input, "unmark", tasks.size());
        String unmarkedTask = tasks.unmark(taskNumber);
        storage.saveTasks(tasks.getTasks());
        return ui.getTaskUnmarkedMessage(unmarkedTask);
    }

    /**
     * Deletes a task and saves the shortened list.
     *
     * @param input full delete command
     * @return task-deleted response
     * @throws BobException if the task number is invalid
     * @throws IOException if the task list cannot be saved
     */
    private String deleteTask(String input) throws BobException, IOException {
        int taskNumber = Parser.parseTaskNumber(input, "delete", tasks.size());
        Task removedTask = tasks.delete(taskNumber);
        storage.saveTasks(tasks.getTasks());
        return ui.getTaskDeletedMessage(removedTask, tasks.size());
    }

    /**
     * Returns the greeting and any problem encountered while loading saved tasks.
     *
     * @return startup message for a graphical UI
     */
    public String getWelcomeMessage() {
        String message = ui.getWelcomeMessage();
        if (loadingError != null) {
            message += "\n\n" + ui.getLoadingErrorMessage(loadingError);
        }
        return message;
    }

    /**
     * Checks whether the user has entered the exit command.
     *
     * @return true after processing {@code bye}
     */
    public boolean isExit() {
        return isExit;
    }

    /**
     * Stores a task and creates its confirmation response.
     *
     * @param task task to add
     * @return confirmation to display
     * @throws IOException if the task list cannot be saved
     */
    private String addTask(Task task) throws IOException {
        assert task != null : "Parsed task must not be null";
        tasks.add(task);
        storage.saveTasks(tasks.getTasks());
        return ui.getTaskAddedMessage(task, tasks.size());
    }

    /**
     * Starts Bob using the default task storage path.
     *
     * @param args command-line arguments, which are not used
     */
    public static void main(String[] args) {
        new Bob("./data/bob.txt").run();
    }
}
