package bob.ui;

import java.io.IOException;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/**
 * Displays one chat message beside a label identifying its speaker.
 */
public class DialogBox extends HBox {
    @FXML
    private Label dialog;

    @FXML
    private Label avatar;

    private DialogBox(String text, String speaker) {
        try {
            FXMLLoader loader = new FXMLLoader(MainWindow.class.getResource("/view/DialogBox.fxml"));
            loader.setController(this);
            loader.setRoot(this);
            loader.load();
        } catch (IOException e) {
            throw new IllegalStateException("Unable to load a dialog box.", e);
        }

        dialog.setText(text);
        avatar.setText(speaker);
        dialog.maxWidthProperty().bind(widthProperty().multiply(0.75));
    }

    /**
     * Creates a right-aligned message entered by the user.
     *
     * @param text message entered by the user
     * @return user dialog box
     */
    public static DialogBox getUserDialog(String text) {
        return new DialogBox(text, "You");
    }

    /**
     * Creates a left-aligned response from Bob.
     *
     * @param text response generated by Bob
     * @return Bob dialog box
     */
    public static DialogBox getBobDialog(String text) {
        DialogBox dialogBox = new DialogBox(text, "Bob");
        dialogBox.flip();
        return dialogBox;
    }

    /**
     * Moves Bob's label to the left and applies the reply bubble style.
     */
    private void flip() {
        ObservableList<Node> children = FXCollections.observableArrayList(getChildren());
        FXCollections.reverse(children);
        getChildren().setAll(children);
        setAlignment(Pos.TOP_LEFT);
        dialog.getStyleClass().add("reply-label");
        avatar.getStyleClass().add("bob-avatar");
    }
}
